Key Capabilities
Spaces is a highly performant and scalable object storage solution with a built-in CDN. It’s excellent for storing unstructured files/data for various applications, including data analytics workflows, training artificial intelligence models, log files generated by applications, and video streaming applications. Spaces enables multiple users to access these files simultaneously, preventing performance and productivity bottlenecks. You can also use Spaces to host static assets and user-generated content (e.g., image and sound files) and store log files.

Spaces complements local storage and is designed to help businesses grow and scale on DigitalOcean. Spaces is S3 compatible, allowing you to use the large ecosystem of S3 tools, utilities, and plugins to store and retrieve unstructured data using an HTTP API. Here are some key capabilities:

Spaces supports 800 requests per second (RPS) for read/write transactions. As Spaces is accessed via HTTP-based API commands known as Requests (such as PUT, GET, DELETE), the RPS metric tells you how many such requests can be handled by the storage system in a second.
Data transfer to and from Spaces is automatically encrypted with HTTPS.
Spaces also supports 1500 RPS (any operation) per IP. Higher RPS numbers help businesses run their applications smoothly and avoid performance degradation issues caused by slow storage devices.
Spaces also comes with a free built-in content delivery network that caches assets across 45+ global CDN locations, including several locations in the APAC region, including Mumbai, Singapore, Hong Kong, Sydney, and Melbourne.

Regulatory compliance
Many laws and regulations govern data collection, storage, and sharing. An essential aspect of some of these regulations is that they often prohibit storing certain data outside national boundaries. Using Spaces Object storage for storing unstructured data at scale within the Bangalore data center can be an important part of your company’s overall regulatory compliance strategy.

Excellent for storing cloud backups
No company is immune from outages or natural disasters, so businesses must protect themselves and their customer data from unforeseen situations. Today’s cloud landscape is not just about virtual machines, it is also about containers, managed databases, applications, and more. Backing up the data within these applications can help businesses avoid data loss, increase customer satisfaction and ensure customer retention. You can use Spaces as an endpoint to store frequent backups of your DigitalOcean services, including docker containers and managed databases. If your business serves customers globally, you can use Spaces Object storage in the Bangalore data center as an essential part of your disaster recovery strategy.
